main: de.dxvampi.DeEssentials
version: 1.0.0a
name: DeEssentials
author: dxvampi
api-version: 1.13
commands:
  ping:
    description: Pong!
  deessentials:
    description: Main command for De-Essentials
    aliases:
      - dessentials
      - essentials
  uptime:
    description: Uptime of the server
    aliases:
      - upt
      - serveruptime
      - supt

permissions:
  deessentials.maincommand:
    description: Allow players to use /deessentials or any of the alias
    default: true
  deessentials.maincommand.get:
    description: Allow players to see info about the plugin
    default: op
  deessentials.maincommand.date:
    description: Allow players to see the actual date
    default: true
  deessentials.maincommand.version:
    description: Allow players to see the current plugin's version
    default: op
  deessentials.uptime:
    description: Allow players to see the server uptime
    default: op
  deessentials.maincommand.help:
    description: Allow players to see help about the plugin commands
    default: true