main: de.dxvampi.DeEssentials
version: 1.0.0a
name: DeEssentials
author: dxvampi
api-version: 1.13
commands:
  deessentials:
    description: Main command for De-Essentials
    aliases:
      - dessentials
      - essentials